apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: robert
  labels:
    app: whoami
    kind: backend
spec:
  containers:
    - name: hello
      resources:
        limits:
          cpu: "31"
        requests:
          cpu: "31"
      image: pingbo/whoami
