apiVersion: v1
kind: Service
metadata:
  labels:
    run: web-app
  name: web-app
  namespace: vilvert
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web-app
  sessionAffinity: None
  type: ClusterIP
