apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: vilvert
spec:
  replicas: 4
  selector:
    matchLabels:
      service: web-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: 0
  minReadySeconds: 30
  template:
    metadata:
      labels:
        run: web-app
        app: web-app
        service: web-app
    spec:
      containers:
      - name: web-app
        image: robertvilvert/frontend:1.0
        resources:
          requests:
            cpu: "0.1"
            memory: "128Mi"
          limits:
            cpu: "0.3"
            memory: "512Mi"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort: 80
