apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: vilvert
  labels:
    app: whoami
    kind: backend
spec:
  containers:
    - name: hello
      resources:
        limits:
          cpu: "1"
          memory: 256Mi
        requests:
          cpu: "0.5"
          memory: 128Mi
      image: pingbo/whoami
