apiVersion: v1
kind: Pod
metadata:
  name: web-test
  namespace: vilvert
  labels:
    app: web-test
    kind: web
spec:
  containers:
    - name: whoami
      image: pingbo/whoami
      ports:
        - containerPort: 8000
      command: ["not","command"]
