apiVersion: v1
kind: Pod
metadata:
  name: whoami
  namespace: vilvert
  labels:
    app: whoami
    kind: web
spec:
  containers:
    - name: whoami
      image: pingbo/whoami
      ports:
        - containerPort: 8000
